# File: .github/workflows/zap_scan.yml

name: refsnider.me DAST scan

on: [push]

permissions: read-all

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan main website
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://www.refsnider.me/'
